export const F_TYPES = [
	'COMMON',
	'CONDO',
	'CORRIDOR',
	'RESERVE'
]

export const AREA_NAMES = [
	"Mount Pleasant West (104)",
	"Centennial Scarborough (133)",
	"Wexford/Maryvale (119)",
	"Milliken (130)",
	"Church-Yonge Corridor (75)",
	"Stonegate-Queensway (16)",
	"Eglinton East (138)",
	"Wychwood (94)",
	"Parkwoods-Donalda (45)",
	"Lawrence Park South (103)",
	"Runnymede-Bloor West Village (89)",
	"Brookhaven-Amesbury (30)",
	"Morningside (135)",
	"Cabbagetown-South St.James Town (71)",
	"Rosedale-Moore Park (98)",
	"West Humber-Clairville (1)",
	"Yonge-Eglinton (100)",
	"Dorset Park (126)",
	"St.Andrew-Windfields (40)",
	"Flemingdon Park (44)",
	"Islington-City Centre West (14)",
	"Lambton Baby Point (114)",
	"Niagara (82)",
	"South Riverdale (70)",
	"The Beaches (63)",
	"Edenbridge-Humber Valley (9)",
	"Corso Italia-Davenport (92)",
	"Casa Loma (96)",
	"Rexdale-Kipling (4)",
	"Henry Farm (53)",
	"Maple Leaf (29)",
	"Kennedy Park (124)",
	"Waterfront Communities-The Island (77)",
	"Princess-Rosethorn (10)",
	"Bayview Woods-Steeles (49)",
	"Danforth (66)",
	"Lawrence Park North (105)",
	"Mount Dennis (115)",
	"Clairlea-Birchmount (120)",
	"Humbermede (22)",
	"Woodbine Corridor (64)",
	"South Parkdale (85)",
	"Kingsway South (15)",
	"L'Amoreaux (117)",
	"Beechborough-Greenbrook (112)",
	"Palmerston-Little Italy (80)",
	"Regent Park (72)",
	"Guildwood (140)",
	"Eringate-Centennial-West Deane (11)",
	"Little Portugal (84)",
	"Bathurst Manor (34)",
	"Old East York (58)",
	"Clanton Park (33)",
	"York University Heights (27)",
	"Englemount-Lawrence (32)",
	"Bay Street Corridor (76)",
	"Long Branch (19)",
	"Malvern (132)",
	"Westminster-Branson (35)",
	"High Park North (88)",
	"Bridle Path-Sunnybrook-York Mills (41)",
	"Roncesvalles (86)",
	"Bedford Park-Nortown (39)",
	"Yorkdale-Glen Park (31)",
	"Highland Creek (134)",
	"Junction Area (90)",
	"Humewood-Cedarvale (106)",
	"Danforth East York (59)",
	"Pleasant View (46)",
	"Yonge-St.Clair (97)",
	"Trinity-Bellwoods (81)",
	"Newtonbrook East (50)",
	"West Hill (136)",
	"Ionview (125)",
	"North St.James Town (74)",
	"Keelesdale-Eglinton West (110)",
	"Rockcliffe-Smythe (111)",
	"Oakwood Village (107)",
	"Dovercourt-Wallace Emerson-Junction (93)",
	"Pelmo Park-Humberlea (23)",
	"Thorncliffe Park (55)",
	"Tam O'Shanter-Sullivan (118)",
	"Woodbine-Lumsden (60)",
	"East End-Danforth (62)",
	"Willowdale East (51)",
	"New Toronto (18)",
	"Weston-Pellam Park (91)",
	"Taylor-Massey (61)",
	"Downsview-Roding-CFB (26)",
	"Forest Hill North (102)",
	"Woburn (137)",
	"Kingsview Village-The Westway (6)",
	"O'Connor-Parkview (54)",
	"Broadview North (57)",
	"Rouge (131)",
	"Markland Wood (12)",
	"Alderwood (20)",
	"Bayview Village (52)",
	"Oakridge (121)",
	"Caledonia-Fairbank (109)",
	"Leaside-Bennington (56)",
	"Mimico (includes Humber Bay Shores) (17)",
	"Scarborough Village (139)",
	"Black Creek (24)",
	"Weston (113)",
	"Cliffcrest (123)",
	"Dufferin Grove (83)",
	"University (79)",
	"Glenfield-Jane Heights (25)",
	"Annex (95)",
	"Mount Pleasant East (99)",
	"Steeles (116)",
	"Rustic (28)",
	"Victoria Village (43)",
	"Lansing-Westgate (38)",
	"Forest Hill South (101)",
	"Greenwood-Coxwell (65)",
	"Moss Park (73)",
	"Mount Olive-Silverstone-Jamestown (2)",
	"Bendale (127)",
	"Agincourt South-Malvern West (128)",
	"Elms-Old Rexdale (5)",
	"Etobicoke West Mall (13)",
	"Willowdale West (37)",
	"Birchcliffe-Cliffside (122)",
	"Humber Heights-Westmount (8)",
	"Hillcrest Village (48)",
	"Willowridge-Martingrove-Richview (7)",
	"North Riverdale (68)",
	"Newtonbrook West (36)",
	"Humber Summit (21)",
	"Blake-Jones (69)",
	"Banbury-Don Mills (42)",
	"Don Valley Village (47)",
	"Agincourt North (129)",
	"High Park-Swansea (87)",
	"Kensington-Chinatown (78)",
	"Playter Estates-Danforth (67)",
	"Briar Hill-Belgravia (108)",
	"Thistletown-Beaumond Heights (3)"
]

export const ZONES = [
	"RM",
	"RT",
	"OR",
	"CRE",
	"UNASSIGNED",
	"CL",
	"U",
	"R",
	"RS",
	"EC",
	"O",
	"RA",
	"EO",
	"IE",
	"OM",
	"TBD",
	"I",
	"RAC",
	"IH",
	"OG",
	"IPW",
	"RD",
	"IS",
	"OC",
	"CR",
	"EH",
	"EL",
	"E",
	"UT",
	"ON"
]